-- Active: 1670331581859@@127.0.0.1@3307@ansdb

DROP table  `CADOP`;

-- Criando tabela
CREATE TABLE CADOP(  
    `Registro_ANS` INT,
    `CNPJ` VARCHAR(255),
    `Razao_Social` VARCHAR(255),
    `Nome_Fantasia` VARCHAR(255),
    `Modalidade` VARCHAR(255),
    `Logradouro` VARCHAR(255),
    `Numero` VARCHAR(255),
    `Complemento` VARCHAR(255),
    `Bairro` VARCHAR(255),
    `Cidade` VARCHAR(255),
    `UF` VARCHAR(255),
    `CEP` VARCHAR(255),
    `DDD` VARCHAR(255),
    `Telefone` VARCHAR(255),
    `Fax` VARCHAR(255),
    `Endereco_eletronico` VARCHAR(255),
    `Representante` VARCHAR(255),
    `Cargo_Representante` VARCHAR(255),
    `Data_Registro_ANS` VARCHAR(255),
    INDEX (Registro_ANS)
) COMMENT '';


-- Carga cadastro operadoras
LOAD DATA INFILE '/var/lib/mysql-files/rel.csv'
INTO TABLE CADOP
CHARACTER SET latin1
FIELDS TERMINATED BY ';'
ENCLOSED BY '"' LINES
TERMINATED BY '\r\n'
IGNORE 3 LINES

(`Registro_ANS`,`CNPJ`,`Razao_Social`,`Nome_Fantasia`,`Modalidade`,
`Logradouro`,`Numero`,`Complemento`,`Bairro`,`Cidade`,
`UF`,`CEP`,`DDD`,`Telefone`,`Fax`,
`Endereco_eletronico`,`Representante`,`Cargo_Representante`,@Data_Registro_ANS)
SET 
Data_Registro_ANS = STR_TO_DATE(@Data_Registro_ANS, '%d/%m/%Y');

DROP TABLE `EVENTOS`;
CREATE TABLE EVENTOS(  
     DATA DATE,
     REG_ANS INT,
     CD_CONTA_CONTABIL varchar (255),
     DESCRICAO varchar (255),
     VL_SALDO_INICIAL DECIMAL (20,2),
     VL_SALDO_FINAL DECIMAL (20,2),
     TRIMESTRE INT,
     INDEX (DATA, REG_ANS, TRIMESTRE, DESCRICAO)
);

-- Carga 2021 1
LOAD DATA INFILE '/var/lib/mysql-files/1T2021.csv'
INTO TABLE EVENTOS
CHARACTER SET latin1
FIELDS TERMINATED BY ';'
ENCLOSED BY '"' LINES
TERMINATED BY '\r\n'
IGNORE 1 LINES
(@DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, @VL_SALDO_FINAL, @TRIMESTRE)
SET 
DATA = STR_TO_DATE(@DATA, '%d/%m/%Y'),
VL_SALDO_FINAL = REPLACE(@VL_SALDO_FINAL, ',', '.'),
TRIMESTRE = 1;


-- Carga 2021 2
LOAD DATA INFILE '/var/lib/mysql-files/2T2021.csv'
INTO TABLE EVENTOS
CHARACTER SET latin1
FIELDS TERMINATED BY ';'
ENCLOSED BY '"' LINES
TERMINATED BY '\r\n'
IGNORE 1 LINES
(@DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, @VL_SALDO_FINAL, @TRIMESTRE)
SET 
DATA = STR_TO_DATE(@DATA, '%d/%m/%Y'),
VL_SALDO_FINAL = REPLACE(@VL_SALDO_FINAL, ',', '.'),
TRIMESTRE = 2;


-- Carga 2021 3
LOAD DATA INFILE '/var/lib/mysql-files/3T2021.csv'
INTO TABLE EVENTOS
CHARACTER SET latin1
FIELDS TERMINATED BY ';'
ENCLOSED BY '"' LINES
TERMINATED BY '\r\n'
IGNORE 1 LINES
(@DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, @VL_SALDO_FINAL, @TRIMESTRE)
SET 
DATA = STR_TO_DATE(@DATA, '%d/%m/%Y'),
VL_SALDO_FINAL = REPLACE(@VL_SALDO_FINAL, ',', '.'),
TRIMESTRE = 3;


-- Carga 2021 4
LOAD DATA INFILE '/var/lib/mysql-files/4T2021.csv'
INTO TABLE EVENTOS
CHARACTER SET latin1
FIELDS TERMINATED BY ';'
ENCLOSED BY '"' LINES
TERMINATED BY '\r\n'
IGNORE 1 LINES
(DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, @VL_SALDO_INICIAL, @VL_SALDO_FINAL, @TRIMESTRE)
SET 
VL_SALDO_FINAL = REPLACE(@VL_SALDO_FINAL, ',', '.'),
VL_SALDO_INICIAL = REPLACE(@VL_SALDO_INICIAL, ',', '.'),
TRIMESTRE = 4;





-- Carga 2022 1
LOAD DATA INFILE '/var/lib/mysql-files/1T2022.csv'
INTO TABLE EVENTOS
CHARACTER SET latin1
FIELDS TERMINATED BY ';'
ENCLOSED BY '"' LINES
TERMINATED BY '\r\n'
IGNORE 1 LINES
(@DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, @VL_SALDO_INICIAL, @VL_SALDO_FINAL, @TRIMESTRE)
SET 
DATA = STR_TO_DATE(@DATA, '%Y/%m/%d'),
VL_SALDO_FINAL = REPLACE(@VL_SALDO_FINAL, ',', '.'),
VL_SALDO_INICIAL = REPLACE(@VL_SALDO_INICIAL, ',', '.'),
TRIMESTRE = 1;

-- Carga 2022 2
LOAD DATA INFILE '/var/lib/mysql-files/2T2022.csv'
INTO TABLE EVENTOS
CHARACTER SET latin1
FIELDS TERMINATED BY ';'
ENCLOSED BY '"' LINES
TERMINATED BY '\r\n'
IGNORE 1 LINES
(@DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, @VL_SALDO_INICIAL, @VL_SALDO_FINAL, @TRIMESTRE)
SET 
DATA = STR_TO_DATE(@DATA, '%d/%m/%Y'),
VL_SALDO_FINAL = REPLACE(@VL_SALDO_FINAL, ',', '.'),
VL_SALDO_INICIAL = REPLACE(@VL_SALDO_INICIAL, ',', '.'),
TRIMESTRE = 2;

-- Carga 2022 3

LOAD DATA INFILE '/var/lib/mysql-files/3T2022.csv'
INTO TABLE EVENTOS
CHARACTER SET latin1
FIELDS TERMINATED BY ';'
ENCLOSED BY '"' LINES
TERMINATED BY '\r\n'
IGNORE 1 LINES
(DATA, REG_ANS, CD_CONTA_CONTABIL, DESCRICAO, @VL_SALDO_INICIAL, @VL_SALDO_FINAL, @TRIMESTRE)
SET 
VL_SALDO_FINAL = REPLACE(@VL_SALDO_FINAL, ',', '.'),
VL_SALDO_INICIAL = REPLACE(@VL_SALDO_INICIAL, ',', '.'),
TRIMESTRE = 3;

SELECT reg_ans, sum(`VL_SALDO_FINAL`) from `EVENTOS` WHERE `DESCRICAO` = 'EVENTOS/ SINISTROS CONHECIDOS OU AVISADOS  DE ASSISTÊNCIA A SAÚDE MEDICO HOSPITALAR '
group by reg_ans;


SELECT * from `CADOP`;

-- Quais as 10 operadoras que mais tiveram 
-- despesas com "EVENTOS/ SINISTROS CONHECIDOS OU AVISADOS  DE ASSISTÊNCIA A SAÚDE MEDICO HOSPITALAR" 
--no último trimestre?


SELECT  YEAR(DATA) ANO, Razao_Social , TRIMESTRE, SUM(VL_SALDO_FINAL) saldo,
   RANK() OVER (PARTITION BY
                     YEAR(DATA), TRIMESTRE
                 ORDER BY
                     SUM(VL_SALDO_FINAL) DESC
                ) as ranking 
from CADOP C
join EVENTOS E on (C.Registro_ANS = E.REG_ANS)
where CD_CONTA_CONTABIL = '41111'
AND YEAR(DATA) = (SELECT  MAX(YEAR(DATA)) FROM EVENTOS)
AND TRIMESTRE  = (SELECT MAX(TRIMESTRE) FROM EVENTOS WHERE YEAR(DATA) = (SELECT  MAX(YEAR(DATA)) FROM EVENTOS) )
GROUP BY  YEAR(DATA),TRIMESTRE,Razao_Social
LIMIT 10;

--Quais as 10 operadoras que mais tiveram despesas com "EVENTOS/ SINISTROS CONHECIDOS OU AVISADOS  DE ASSISTÊNCIA A SAÚDE MEDICO HOSPITALAR" no último ano?
SELECT  Razao_Social , SUM(VL_SALDO_FINAL) saldo
from CADOP C
join EVENTOS E on (C.Registro_ANS = E.REG_ANS)
where CD_CONTA_CONTABIL = '41111'
AND YEAR(DATA) = (SELECT  MAX(YEAR(DATA)) FROM EVENTOS)
GROUP BY  Razao_Social
ORDER BY SALDO DESC
LIMIT 10;

